#!/usr/bin/env python3
from pathlib import Path
import hashlib
import json

ROOT = Path.cwd()
VERSION = "3.7.14"


def replace_once(path: str, old: str, new: str) -> None:
    target = ROOT / path
    text = target.read_text(encoding="utf-8")
    if old not in text:
        raise SystemExit(f"missing expected text in {path}: {old[:96]!r}")
    target.write_text(text.replace(old, new, 1), encoding="utf-8")


replace_once("edis-evidence-exporter.php", " * Version: 3.7.13", " * Version: 3.7.14")
replace_once(
    "edis-evidence-exporter.php",
    "define( 'EDIS_EVIDENCE_EXPORTER_VERSION', '3.7.13' );",
    "define( 'EDIS_EVIDENCE_EXPORTER_VERSION', '3.7.14' );",
)
replace_once(
    "edis-evidence-exporter.php",
    "define( 'EDIS_EVIDENCE_BUILD_PLATFORM_VERSION', '3.7.13' );",
    "define( 'EDIS_EVIDENCE_BUILD_PLATFORM_VERSION', '3.7.14' );",
)

package = json.loads((ROOT / "package.json").read_text(encoding="utf-8"))
package["version"] = VERSION
(ROOT / "package.json").write_text(json.dumps(package, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")

package_lock = json.loads((ROOT / "package-lock.json").read_text(encoding="utf-8"))
package_lock["version"] = VERSION
package_lock["packages"][""]["version"] = VERSION
(ROOT / "package-lock.json").write_text(json.dumps(package_lock, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")

readme = ROOT / "README.md"
text = readme.read_text(encoding="utf-8")
old = "Version `3.7.13`, generated by EDIS Enterprise Deterministic Build Platform `3.7.13`."
new = "Version `3.7.14`, generated by EDIS Enterprise Deterministic Build Platform `3.7.14`."
if old not in text:
    raise SystemExit("README version line drifted")
text = text.replace(old, new, 1)
old_intro = "Version 3.7.13 is a bounded degraded-admin recovery patch. Unsupported deterministic PHP runtime is handled **before `Bootstrap`** by `edis_evidence_exporter_runtime_notice`; that pre-Bootstrap path does not register the recovery shell. Once the deterministic runtime is supported and `Bootstrap` runs, the three current fail-closed degraded causes—installation-integrity failure, invalid configuration, and private-storage failure—route through `DegradedModeIntegration`, which restores a minimal `EDIS Evidence` Diagnostics / Recovery surface without initializing the operational export graph. Healthy `AdminModule` behavior is unchanged, frozen evidence contracts remain unchanged, and worker implementation compatibility deliberately remains `3.7.12`."
new_intro = "Version 3.7.14 is the bounded correctness-closure release for exported-source privacy projection, truthful failed-observation semantics, per-artifact temporal provenance, manifest-authoritative release inventory, generated-validation output isolation, machine-checked collector documentation, truthful recovery scheduling state, and exact final-build qualification. Frozen public evidence contracts remain unchanged; worker implementation compatibility advances to `3.7.14`, so incomplete jobs created under 3.7.12 must be recreated."
if old_intro not in text:
    raise SystemExit("README current-release introduction drifted")
text = text.replace(old_intro, new_intro, 1)
marker = "## 3.7.13 degraded diagnostics recovery\n"
section = """## 3.7.14 correctness closure

Release 3.7.14 applies one shared recursive/path-aware privacy projection before exported source evidence is committed, distinguishes successful empty observations from failed Elementor/WordPress observations, stamps committed artifacts with truthful observation/derivation time, and persists one packaging start time for deterministic retries. `elementor_document_source` continues to use the immutable snapshot capture time.

Release construction is now manifest-authoritative: install inventory comes from `plugin.manifest.json` entries with `installable=true`, source inventory comes from the manifest plus `composer.lock`, undeclared ordinary files fail closed, and the release report binds plugin/worker identity to manifest, critical-file and source-inventory SHA-256 fingerprints. Generated validation evidence remains under `release-build/validation-evidence/` and is never source authority.

Retryable failures clear the active REST lease state before using the existing recovery scheduler and persist the scheduler's actual result. Non-retryable integrity failures have no future retry deadline or active recovery schedule. Collector encyclopedia Technical IDs/schema versions are checked against the active manifest. Bundle Schema `3.3.0`, Shared Artifact Envelope `2.0.0`, Package Manifest `2.1.0`, Selection Snapshot `1.2.0`, EDIS-CJ-2 and EDIS-ZIP-1 remain unchanged.

"""
if "## 3.7.14 correctness closure" not in text:
    if marker not in text:
        raise SystemExit("README historical 3.7.13 marker missing")
    text = text.replace(marker, section + marker, 1)
text = text.replace("version 3.7.13 preserves it unchanged", "version 3.7.14 preserves it unchanged", 1)
text = text.replace("In `WP_ENVIRONMENT_TYPE=local`, EDIS 3.7.13 prefers", "In `WP_ENVIRONMENT_TYPE=local`, EDIS 3.7.14 prefers", 1)
readme.write_text(text, encoding="utf-8")

wp_readme = ROOT / "readme.txt"
text = wp_readme.read_text(encoding="utf-8")
if "Stable tag: 3.7.13" not in text:
    raise SystemExit("readme.txt stable tag drifted")
text = text.replace("Stable tag: 3.7.13", "Stable tag: 3.7.14", 1)
old_desc = "Version 3.7.13 is a bounded degraded-admin recovery patch. Unsupported deterministic PHP runtime is handled before `Bootstrap` by `edis_evidence_exporter_runtime_notice` and does not register the recovery shell. After a supported runtime reaches Bootstrap, the three current degraded causes—installation-integrity failure, invalid configuration, and private-storage failure—use `DegradedModeIntegration` to retain a minimal EDIS Evidence Diagnostics / Recovery surface without initializing export services. Healthy-mode behavior and frozen public evidence contracts are unchanged, and worker implementation compatibility remains 3.7.12."
new_desc = "Version 3.7.14 closes eight bounded correctness defects without changing frozen public evidence schemas: shared pre-commit privacy projection, failure-vs-empty observation truth, orchestrator-stamped provenance, manifest-authoritative release inventory and build fingerprinting, generated-validation output isolation, machine-checked collector documentation, truthful recovery scheduling state, and exact final-build runtime qualification. Worker implementation compatibility advances to 3.7.14."
if old_desc not in text:
    raise SystemExit("readme.txt current-release description drifted")
text = text.replace(old_desc, new_desc, 1)
old_faq = "Jobs are compatible by worker implementation identity, not merely plugin release number. A persisted job created by worker implementation 3.7.11 must be recreated under 3.7.12. Release 3.7.13 intentionally keeps worker implementation compatibility at 3.7.12, so otherwise-compatible persisted 3.7.12 jobs are not invalidated by this admin-only patch."
new_faq = "Jobs are compatible by worker implementation identity, not merely plugin release number. Release 3.7.14 advances the worker implementation identity to 3.7.14 because committed-artifact provenance and resume semantics changed. Incomplete jobs created under worker 3.7.12 are not migrated in place and must be recreated."
if old_faq not in text:
    raise SystemExit("readme.txt resume FAQ drifted")
text = text.replace(old_faq, new_faq, 1)
changelog_marker = "= 3.7.13 =\n"
changelog_314 = """= 3.7.14 =

* Adds one shared recursive/path-aware pre-commit privacy projection for exported raw-value source evidence while preserving immutable private input bytes.
* Distinguishes failed required observations from successful empty observations and preserves valid optional evidence only as bounded PARTIAL results.
* Stores truthful per-component `observed_at` provenance and one persisted `packaging_started_at`; worker compatibility advances to 3.7.14.
* Makes `plugin.manifest.json` the install/source release inventory authority, fails on undeclared ordinary files, and emits deterministic build fingerprints.
* Keeps generated validation evidence under `release-build/validation-evidence/` and machine-checks both collector encyclopedias against active Technical IDs/schema versions.
* Normalizes failed-job scheduling state through the existing recovery scheduler so released jobs cannot remain `REST_ADVANCE_ACTIVE`.
* Preserves Bundle Schema 3.3.0, Shared Artifact Envelope 2.0.0, Package Manifest 2.1.0, Selection Snapshot 1.2.0, EDIS-CJ-2 and EDIS-ZIP-1.

"""
if "= 3.7.14 =" not in text:
    if changelog_marker not in text:
        raise SystemExit("readme.txt changelog marker missing")
    text = text.replace(changelog_marker, changelog_314 + changelog_marker, 1)
wp_readme.write_text(text, encoding="utf-8")

changelog = ROOT / "CHANGELOG.md"
text = changelog.read_text(encoding="utf-8")
if "## 3.7.14" not in text:
    marker = "## 3.7.13\n"
    section = """## 3.7.14

- Adds a shared deterministic recursive/path-aware privacy projection before exported raw-value source artifacts are committed; private immutable snapshot bytes and their authoritative hashes remain exact.
- Separates successful empty Elementor/WordPress observations from failed observations, including bounded PARTIAL Environment evidence for optional URL-normalization failure.
- Stamps committed artifacts with truthful `observed_at` provenance and persists one `packaging_started_at` across packaging retries; worker implementation compatibility advances to `3.7.14`.
- Makes `plugin.manifest.json` authoritative for release inventory, rejects undeclared ordinary workspace files, validates all intended-equal release version authorities, and emits manifest/critical/source-inventory build fingerprints.
- Moves normative generated validation reports under `release-build/validation-evidence/` and adds machine-checked Technical ID/schema synchronization for both collector encyclopedias.
- Normalizes retryable and non-retryable failure scheduling through the existing recovery state machine so released failures cannot retain `REST_ADVANCE_ACTIVE`.
- Adds focused privacy, observation, provenance, release-authority, documentation and recovery regression coverage plus exact final-build WordPress/Elementor qualification.
- Preserves Bundle Schema `3.3.0`, Shared Artifact Envelope `2.0.0`, Package Manifest `2.1.0`, Selection Snapshot `1.2.0`, EDIS-CJ-2, EDIS-ZIP-1 and Browser/Python ownership boundaries.

"""
    if marker not in text:
        raise SystemExit("CHANGELOG historical marker missing")
    text = text.replace(marker, section + marker, 1)
changelog.write_text(text, encoding="utf-8")

manifest_path = ROOT / "plugin.manifest.json"
manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
manifest["platform_version"] = VERSION
manifest["plugin"]["version"] = VERSION
manifest["build"]["version"] = VERSION
manifest["build"]["platform_version"] = VERSION
required_additions = {
    "src/Infrastructure/Support/PrivacyProjection.php": True,
    "tests/Unit/CorrectnessClosure314Test.php": False,
    "tests/Unit/EnvironmentObservation314Test.php": False,
    "tests/Unit/ReleaseAuthority314Test.php": False,
    "tests/release-authority-314.py": False,
}
entries = manifest.get("files")
if not isinstance(entries, list):
    raise SystemExit("manifest files authority missing")
existing = {entry.get("path"): entry for entry in entries if isinstance(entry, dict)}
for path, installable in required_additions.items():
    if path in existing:
        if existing[path].get("installable") is not installable:
            raise SystemExit(f"manifest installable mismatch for {path}")
        continue
    entries.append({"installable": installable, "path": path})
entries.sort(key=lambda entry: str(entry["path"]).encode("utf-8"))
manifest_path.write_text(
    json.dumps(manifest, ensure_ascii=False, sort_keys=True, separators=(",", ":")) + "\n",
    encoding="utf-8",
)

critical_path = ROOT / "config/critical-files.json"
critical = json.loads(critical_path.read_text(encoding="utf-8"))
critical["plugin_version"] = VERSION
critical_files = critical.get("files")
if not isinstance(critical_files, dict):
    raise SystemExit("critical-files authority missing")
critical_files.setdefault("src/Infrastructure/Support/PrivacyProjection.php", "")
for relative in sorted(critical_files):
    path = ROOT / relative
    if not path.is_file() or path.is_symlink():
        raise SystemExit(f"critical file unavailable: {relative}")
    critical_files[relative] = "sha256:" + hashlib.sha256(path.read_bytes()).hexdigest()
critical_path.write_text(
    json.dumps(critical, ensure_ascii=False, sort_keys=True, separators=(",", ":")) + "\n",
    encoding="utf-8",
)
