<?php
/** @var array<string,list<\EDIS\EvidenceExporter\Infrastructure\Collector\CollectorDefinition> $collectorGroups */
/** @var array<string,mixed> $defaults */
/** @var string $requestedExportScope */
$selected=array_fill_keys((array)($defaults['collectors']??[]),true);
?>
<div class="wrap edis-admin" data-edis-page="create-export">
<h1><?php echo esc_html__('Create Source Evidence Export','edis-evidence-exporter'); ?></h1>
<p class="edis-lead"><?php echo esc_html__('Choose an explicit document scope. EDIS exports saved source evidence and the minimum shared context Python needs; it does not score UX or infer browser geometry.','edis-evidence-exporter'); ?></p>
<div id="edis-inspector-selection" class="edis-panel edis-hidden" aria-live="polite"></div>
<div class="notice notice-info inline"><p><?php echo esc_html__('Version 3.7 captures immutable saved-source snapshots, uses lossless EDIS-CJ-2 canonicalization, validates document scope before creating a job, and runs final processors only after source collection and index construction.','edis-evidence-exporter'); ?></p></div>
<form id="edis-export-form" novalidate>
<section class="edis-panel"><h2><?php echo esc_html__('1. Export scope','edis-evidence-exporter'); ?></h2><fieldset class="edis-card-grid"><legend class="screen-reader-text"><?php echo esc_html__('Choose export scope','edis-evidence-exporter'); ?></legend>
<?php $scopes=['SINGLE_DOCUMENT'=>__('Single document','edis-evidence-exporter'),'MULTIPLE_DOCUMENTS'=>__('Multiple documents','edis-evidence-exporter'),'METADATA_ONLY'=>__('Metadata only','edis-evidence-exporter'),'ENTIRE_SITE'=>__('Entire site evidence','edis-evidence-exporter')];foreach($scopes as $value=>$label): ?><label class="edis-choice-card"><input type="radio" name="export_scope" value="<?php echo esc_attr($value); ?>" <?php checked($requestedExportScope,$value); ?>><span><strong><?php echo esc_html($label); ?></strong><small><?php echo esc_html($value==='SINGLE_DOCUMENT'?__('Exactly one Elementor document.','edis-evidence-exporter'):($value==='MULTIPLE_DOCUMENTS'?__('One or more selected Elementor documents.','edis-evidence-exporter'):($value==='METADATA_ONLY'?__('Environment, registries and inventory without saved document source.','edis-evidence-exporter'):__('All editable Elementor documents, bounded by the configured inventory limit.','edis-evidence-exporter')))); ?></small></span></label><?php endforeach; ?></fieldset>
<p><label for="edis-dependency-scope"><strong><?php echo esc_html__('Dependency scope','edis-evidence-exporter'); ?></strong></label> <select id="edis-dependency-scope" name="dependency_scope"><option value="SOURCE_ONLY"><?php echo esc_html__('Page source only','edis-evidence-exporter'); ?></option><option value="REQUIRED_DEPENDENCIES" selected><?php echo esc_html__('Page + required dependencies (recommended)','edis-evidence-exporter'); ?></option><option value="FULL_SITE_CONTEXT"><?php echo esc_html__('Page + full site context','edis-evidence-exporter'); ?></option></select></p>
</section>
<section class="edis-panel"><h2><?php echo esc_html__('2. Privacy mode','edis-evidence-exporter'); ?></h2><fieldset class="edis-card-grid"><legend class="screen-reader-text"><?php echo esc_html__('Choose privacy mode','edis-evidence-exporter'); ?></legend><?php foreach(['Strict'=>__('Strict — minimum source content','edis-evidence-exporter'),'Standard'=>__('Standard — balanced evidence','edis-evidence-exporter'),'Diagnostic'=>__('Diagnostic — additional technical metadata','edis-evidence-exporter')] as $mode=>$label): ?><label class="edis-choice-card"><input type="radio" name="privacy_mode" value="<?php echo esc_attr($mode); ?>" <?php checked(($defaults['privacy_mode']??'Standard'),$mode); ?>><span><strong><?php echo esc_html($label); ?></strong><small><?php echo esc_html($mode==='Strict'?__('Original documents are forcibly excluded.','edis-evidence-exporter'):($mode==='Diagnostic'?__('Use only when authorized to export technical metadata.','edis-evidence-exporter'):__('Recommended for controlled analysis runs.','edis-evidence-exporter'))); ?></small></span></label><?php endforeach; ?></fieldset></section>
<section class="edis-panel"><h2><?php echo esc_html__('3. Source components','edis-evidence-exporter'); ?></h2><p><?php echo esc_html__('Required dependencies and final bundle processors are added automatically.','edis-evidence-exporter'); ?></p><?php foreach($collectorGroups as $group=>$definitions):$selectable=array_filter($definitions,static fn($d)=>$d->selectable);if($selectable===[]){continue;} ?><fieldset class="edis-component-group"><legend><?php echo esc_html(ucwords(str_replace('_',' ',(string)$group))); ?></legend><div class="edis-card-grid"><?php foreach($selectable as $definition): ?><label class="edis-choice-card"><input type="checkbox" name="collectors[]" value="<?php echo esc_attr($definition->id); ?>" <?php checked(isset($selected[$definition->id])||$definition->defaultEnabled); ?>><span><strong><?php echo esc_html(is_rtl()?$definition->labelFa:$definition->label); ?></strong><small><?php echo esc_html(is_rtl()?$definition->descriptionFa:$definition->description); ?></small><span class="edis-meta"><code><?php echo esc_html($definition->id); ?></code><span class="edis-badge" data-state="<?php echo esc_attr($definition->declaredTruthState->value); ?>"><?php echo esc_html($definition->declaredTruthState->value); ?></span></span></span></label><?php endforeach; ?></div></fieldset><?php endforeach; ?></section>
<section class="edis-panel" id="edis-documents-section"><h2><?php echo esc_html__('4. Elementor documents','edis-evidence-exporter'); ?></h2><p><?php echo esc_html__('Use search, the Pages row action, or the Pages bulk action. Single and Multiple scopes cannot start without the required selection.','edis-evidence-exporter'); ?></p><div class="edis-search-row"><label for="edis-document-search"><?php echo esc_html__('Search documents','edis-evidence-exporter'); ?></label><input type="search" id="edis-document-search" class="regular-text" autocomplete="off"><button type="button" class="button" data-edis-action="search-documents"><?php echo esc_html__('Search','edis-evidence-exporter'); ?></button></div><div class="edis-compact-actions"><button type="button" class="button" data-edis-action="select-visible-documents"><?php echo esc_html__('Select visible','edis-evidence-exporter'); ?></button><button type="button" class="button" data-edis-action="clear-documents"><?php echo esc_html__('Clear selected','edis-evidence-exporter'); ?></button></div><div id="edis-document-results" class="edis-document-results" aria-live="polite"><p class="edis-empty-state"><?php echo esc_html__('Search to load Elementor documents.','edis-evidence-exporter'); ?></p></div><div id="edis-document-pagination" class="edis-pagination"></div><p><strong><?php echo esc_html__('Selected documents:','edis-evidence-exporter'); ?></strong> <span id="edis-selected-document-count">0</span></p></section>
<section class="edis-panel"><h2><?php echo esc_html__('5. Effective export options','edis-evidence-exporter'); ?></h2><fieldset class="edis-option-list"><legend class="screen-reader-text"><?php echo esc_html__('Choose export options','edis-evidence-exporter'); ?></legend><label><input type="checkbox" name="options[include_original_documents]" value="1" <?php checked((bool)($defaults['include_original_documents']??false)); ?>> <?php echo esc_html__('Include the original saved Elementor document object. Strict mode overrides this to off.','edis-evidence-exporter'); ?></label><label><input type="checkbox" name="options[include_diagnostic_metadata]" value="1" <?php checked((bool)($defaults['include_diagnostic_metadata']??false)); ?>> <?php echo esc_html__('Include additional operational diagnostic metadata.','edis-evidence-exporter'); ?></label><label><input type="checkbox" name="options[compare_previous_export]" value="1" checked> <?php echo esc_html__('Compare source hashes and bounded counts with the previous completed EDIS export.','edis-evidence-exporter'); ?></label><label><input type="checkbox" name="options[fixture_mode]" value="1"> <?php echo esc_html__('Include controlled real-fixture authoring metadata. This does not create expected findings automatically.','edis-evidence-exporter'); ?></label><label><?php echo esc_html__('Maximum inventory records','edis-evidence-exporter'); ?> <input class="small-text" type="number" name="options[document_inventory_limit]" min="1" max="2000" value="500"></label></fieldset></section>
<section class="edis-panel"><h2><?php echo esc_html__('6. Preflight, review and start','edis-evidence-exporter'); ?></h2><div id="edis-review-summary" class="edis-review-summary" aria-live="polite"></div><div class="edis-actions"><button type="button" class="button" data-edis-action="run-preflight"><?php echo esc_html__('Run preflight','edis-evidence-exporter'); ?></button><button type="submit" class="button button-primary button-hero" disabled><?php echo esc_html__('Start Export','edis-evidence-exporter'); ?></button></div><div id="edis-preflight-result" aria-live="polite"></div><label id="edis-diagnostic-confirm-wrap" class="edis-confirmation edis-hidden"><input type="checkbox" id="edis-diagnostic-confirm"> <?php echo esc_html__('I confirm that I am authorized to create a Diagnostic export.','edis-evidence-exporter'); ?></label></section>
</form>
<section id="edis-job-panel" class="edis-panel edis-hidden"><h2><?php echo esc_html__('Export job','edis-evidence-exporter'); ?></h2><div id="edis-job-live" aria-live="polite"></div><progress id="edis-job-progress" max="100" value="0"><span>0%</span></progress><dl id="edis-job-details" class="edis-definition-list"></dl><div id="edis-job-actions" class="edis-actions"></div></section>
</div>
