<?php /** @var list<\EDIS\EvidenceExporter\Infrastructure\Collector\CollectorDefinition> $definitions */ ?>
<div class="wrap edis-admin edis-help" data-edis-page="help"><h1><?php echo esc_html__('EDIS Evidence Encyclopedia','edis-evidence-exporter'); ?></h1>
<p class="edis-lead"><?php echo esc_html__('The English and Persian explanations below have equal scope. Each entry explains what the evidence is, how it is collected, why Python needs it, and what cannot be concluded from it.','edis-evidence-exporter'); ?></p>
<section class="edis-panel"><h2>Pipeline / روند سیستم</h2><pre>WordPress saved evidence → Browser runtime evidence → Python deterministic truth → LLM explanation</pre><p><?php echo esc_html__('The WordPress plugin does not analyze UX. It exports saved declarations and provenance. Python resolves and evaluates them only after source, runtime, and coverage evidence are verified.','edis-evidence-exporter'); ?></p></section>
<nav class="edis-help-index" aria-label="<?php echo esc_attr__('Evidence component index','edis-evidence-exporter'); ?>"><ul><?php foreach($definitions as $definition): ?><li><a href="#help-<?php echo esc_attr($definition->id); ?>"><?php echo esc_html($definition->label); ?> / <?php echo esc_html($definition->labelFa); ?></a></li><?php endforeach; ?></ul></nav>
<?php foreach($definitions as $definition): $en=$definition->documentation['en']??[];$fa=$definition->documentation['fa']??[];$refs=$definition->documentation['official_references']??[]; ?>
<article class="edis-panel edis-help-entry" id="help-<?php echo esc_attr($definition->id); ?>"><header><h2><?php echo esc_html($definition->label); ?> <span lang="fa" dir="rtl">— <?php echo esc_html($definition->labelFa); ?></span></h2><p><code><?php echo esc_html($definition->id); ?></code> <span class="edis-badge edis-type"><?php echo esc_html($definition->componentType->value); ?></span> <span class="edis-badge" data-state="<?php echo esc_attr($definition->declaredTruthState->value); ?>"><?php echo esc_html($definition->declaredTruthState->value); ?></span></p></header>
<div class="edis-language-columns"><section lang="en" dir="ltr"><h3>English guide</h3><h4>What is this evidence?</h4><p><?php echo esc_html((string)($en['what_is']??$definition->description)); ?></p><h4>How does EDIS retrieve it?</h4><p><?php echo esc_html((string)($en['retrieval']??'')); ?></p><h4>Which fields are exported?</h4><p><?php echo esc_html((string)($en['fields']??'')); ?></p><h4>Why is it important to the pipeline?</h4><p><?php echo esc_html((string)($en['pipeline_importance']??$en['python_usage']??'')); ?></p><h4>How can Python use it?</h4><p><?php echo esc_html((string)($en['python_usage']??'')); ?></p><h4>What reaches the LLM?</h4><p><?php echo esc_html((string)($en['llm_receives']??'')); ?></p><h4>What cannot be concluded?</h4><p><?php echo esc_html((string)($en['cannot_conclude']??'')); ?></p><h4>Version and privacy limits</h4><p><?php echo esc_html((string)($en['version_limitations']??'')); ?></p><p><?php echo esc_html((string)($en['privacy']??'')); ?></p><h4>Troubleshooting</h4><p><?php echo esc_html((string)($en['troubleshooting']??'')); ?></p></section>
<section lang="fa" dir="rtl"><h3>راهنمای فارسی</h3><h4>این داده چیست؟</h4><p><?php echo esc_html((string)($fa['what_is']??$definition->descriptionFa)); ?></p><h4>EDIS چگونه آن را می‌خواند؟</h4><p><?php echo esc_html((string)($fa['retrieval']??'')); ?></p><h4>چه فیلدهایی صادر می‌شوند؟</h4><p><?php echo esc_html((string)($fa['fields']??'')); ?></p><h4>چرا برای Pipeline مهم است؟</h4><p><?php echo esc_html((string)($fa['pipeline_importance']??$fa['python_usage']??'')); ?></p><h4>Python چه استفاده‌ای از آن می‌کند؟</h4><p><?php echo esc_html((string)($fa['python_usage']??'')); ?></p><h4>چه چیزی به مدل زبانی می‌رسد؟</h4><p><?php echo esc_html((string)($fa['llm_receives']??'')); ?></p><h4>چه نتیجه‌ای نمی‌توان گرفت؟</h4><p><?php echo esc_html((string)($fa['cannot_conclude']??'')); ?></p><h4>محدودیت نسخه و حریم خصوصی</h4><p><?php echo esc_html((string)($fa['version_limitations']??'')); ?></p><p><?php echo esc_html((string)($fa['privacy']??'')); ?></p><h4>عیب‌یابی</h4><p><?php echo esc_html((string)($fa['troubleshooting']??'')); ?></p></section></div>
<?php $example=['schema_id'=>$definition->schemaId,'schema_version'=>$definition->schemaVersion,'artifact_type'=>$definition->id,'producer'=>['product'=>'edis-evidence-exporter','version'=>'3.7.11'],'captured_at'=>'2026-06-13T00:00:00Z','canonicalization'=>\EDIS\EvidenceExporter\Infrastructure\Support\CanonicalJson::canonicalizationDescriptor(),'data'=>['component_id'=>$definition->id,'component_type'=>$definition->componentType->value,'source_truth_state'=>$definition->declaredTruthState->value,'source_availability'=>$definition->defaultAvailability->value,'evidence'=>'<typed component payload>','source_references'=>[],'provenance'=>['collector_id'=>$definition->id]],'diagnostics'=>[]]; \EDIS\EvidenceExporter\Infrastructure\Support\CanonicalJson::applyHashes($example); ?>
<details><summary><?php echo esc_html__('Technical contract and example JSON','edis-evidence-exporter'); ?></summary><dl class="edis-definition-list"><dt>Schema</dt><dd><code><?php echo esc_html($definition->schemaId.' '.$definition->schemaVersion); ?></code></dd><dt>Artifact</dt><dd><code><?php echo esc_html($definition->artifactPath); ?></code></dd><dt>Dependencies</dt><dd><pre><?php echo esc_html(wp_json_encode($definition->dependencies,JSON_PRETTY_PRINT|JSON_UNESCAPED_UNICODE)); ?></pre></dd><dt>Official references</dt><dd><?php echo esc_html(implode(', ',array_map('strval',is_array($refs)?$refs:[]))); ?></dd><dt>Example JSON / نمونه JSON</dt><dd><pre><?php echo esc_html(wp_json_encode($example,JSON_PRETTY_PRINT|JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES)); ?></pre></dd></dl></details></article>
<?php endforeach; ?></div>
