<?php
declare(strict_types=1);
namespace EDIS\EvidenceExporter\Admin;
use EDIS\EvidenceExporter\Admin\Page\CreateExportPage;use EDIS\EvidenceExporter\Admin\Page\DataCoveragePage;use EDIS\EvidenceExporter\Admin\Page\DataSourcesPage;use EDIS\EvidenceExporter\Admin\Page\DiagnosticsPage;use EDIS\EvidenceExporter\Admin\Page\HelpPage;use EDIS\EvidenceExporter\Admin\Page\OverviewPage;use EDIS\EvidenceExporter\Admin\Page\SettingsPage;use EDIS\EvidenceExporter\Admin\Settings\SettingsRegistrar;use EDIS\EvidenceExporter\Admin\Settings\SettingsRepository;use EDIS\EvidenceExporter\Admin\View\ViewRenderer;use EDIS\EvidenceExporter\Application\DiagnosticsService;use EDIS\EvidenceExporter\Infrastructure\Collector\CollectorRegistry;use EDIS\EvidenceExporter\Infrastructure\Support\JobStore;use EDIS\EvidenceExporter\Infrastructure\Support\SelectionTokenStore;
final class AdminModule
{
 public function __construct(private readonly string $pluginRoot,private readonly array $config,private readonly CollectorRegistry $registry,private readonly SettingsRepository $settings,private readonly SettingsRegistrar $settingsRegistrar,private readonly JobStore $jobs,private readonly DiagnosticsService $diagnostics,private readonly SelectionTokenStore $selectionTokens){}
 public function register():void{$templates=[];foreach($this->config['pages'] as $page){if(is_array($page)){$templates[(string)$page['id']]=(string)$page['template'];}}$renderer=new ViewRenderer($this->pluginRoot,$templates);$capability=(string)$this->config['capability'];$pages=[new OverviewPage($renderer,$capability,$this->registry,$this->jobs,$this->settings,$this->diagnostics),new CreateExportPage($renderer,$capability,$this->registry,$this->settings),new DataSourcesPage($renderer,$capability,$this->registry),new DataCoveragePage($renderer,$capability,$this->registry,$this->jobs),new DiagnosticsPage($renderer,$capability,$this->diagnostics),new SettingsPage($renderer,$capability,$this->settings),new HelpPage($renderer,$capability,$this->registry)];$menu=new AdminMenu($this->config,$pages);$assets=new AdminAssets($this->config,$menu,$this->selectionTokens);$documentActions=new DocumentActions($capability);add_action('admin_menu',[$menu,'register']);add_action('admin_enqueue_scripts',[$assets,'enqueue']);add_action('admin_init',[$this->settingsRegistrar,'register']);add_action('admin_post_edis_reset_settings',[$this->settingsRegistrar,'reset']);$documentActions->register();}
}
